### ISSUE TITLE
Menu Pengaturan tapi buka window zoom to coordinate

### ISSUE THREAD

**Issue by nurizzahudin** [danylaksono/GeoKKP-GIS#16]
Fitur yang belum available kayaknya mending didisable dulu

**Comment by ismailsunni** [comment]
Sudah diarahkan ke menu pengaturan, tapi masih kosongan.

**Comment by danylaksono** [comment]
layout UI untuk pengaturan ada [di sini](https://github.com/danylaksono/GeoKKP-GIS/blob/develop/ui/pengaturan.ui). Untuk sementara masih kosong sambil nunggu jenis pengaturan yang nanti dibutuhkan untuk layer dan simbologi

**Comment by ismailsunni** [comment]
Sementara dihilangkan dulu menunya, sampai ada kebutuhan lebih jelas.
