### ISSUE TITLE
Buat landing page untuk help?

### ISSUE THREAD

**Issue by nurizzahudin** [danylaksono/GeoKKP-GIS#17]
Rasanya agak aneh aja kalau help spesifik plugin tapi redirect ke komunitas QGIS Indonesia.
Mungkin kalau bentuknya forum dan ada thread khusus mengenai plugin ini akan lebih baik.
Atau dibuat offline help aja kayaknya lebih on point.
Mungkin kalau mau menambah atribusi ke qgis indonesia akan lebih tepat kalau bikin menu lagi semisal about atau credits

**Comment by ismailsunni** [comment]
Ini kayaknya udah kan ya? Tinggal ngisi aja palingan

**Comment by danylaksono** [comment]
Fixed
