### ISSUE TITLE
Pencetakan surat ukur dan peta pendaftaran

### ISSUE THREAD

**Issue by danylaksono** [danylaksono/GeoKKP-GIS#60]
custom qpt dengan menu add template di QGIS (diberikan contoh layout QPT)

**Comment by ivanbusthomi** [comment]
setelah melihat alur pembuatan layout di autocad, sepertinya utk fitur layouting bisa diminimalisir tahapannya dengan langsung ditampilkan ui yg memberi opsi apakah mau membuka template default atau membuka template sendiri yg sudah dibuat sebelumnya.

**Comment by ivanbusthomi** [comment]
fixed in this PR #91
